"""Builds the system and user prompts. Agent/skill files are read verbatim; a runtime contract
is appended so the agent files themselves never need to change."""
from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path

from .config import AGENT_FILE, ANALYSTS, DEPENDS, MAX_CORRECTIONS, MAX_MEDIUM_CORRECTIONS, Paths

SKILL_DIR = Path(".claude/skills/buffett-analysis")


def _strip_frontmatter(text: str) -> str:
    return re.sub(r"\A---\n.*?\n---\n", "", text.replace("\r\n", "\n"), count=1, flags=re.DOTALL).strip()


def load_agent_body(root: Path, agent: str) -> str:
    return _strip_frontmatter((root / ".claude" / "agents" / f"{AGENT_FILE[agent]}.md").read_text(encoding="utf-8"))


def load_skill_body(root: Path) -> str:
    return _strip_frontmatter((root / SKILL_DIR / "SKILL.md").read_text(encoding="utf-8"))


def load_data_rules(root: Path) -> str:
    """The "Data Rules" section of CLAUDE.md. Agents run without project settings (so CLAUDE.md is not loaded for
    them); the rules are passed on verbatim so CLAUDE.md stays their single source."""
    text = (root / "CLAUDE.md").read_text(encoding="utf-8").replace("\r\n", "\n")
    m = re.search(r"^## Data Rules[ \t]*\n(.*?)(?=^## |\Z)", text, re.MULTILINE | re.DOTALL)
    if not m or not m.group(1).strip():
        raise ValueError("CLAUDE.md has no '## Data Rules' section")
    return m.group(1).strip()


# Reference files each agent's instructions tell it to read (valuation.md is named by the moat, management and
# margin-of-safety references for the operating-income-after-taxes definition; the reviewer checks all four).
# They are included in the system prompt so the agent does not spend tool calls reading them.
REFERENCES: dict[str, tuple[str, ...]] = {
    "moat": ("economic_moat", "valuation"),
    "management": ("management_quality", "valuation"),
    "valuation": ("valuation",),
    "business": (),
    "mos": ("margin_of_safety", "valuation"),
    "review": ("economic_moat", "management_quality", "valuation", "margin_of_safety"),
    "report": (),
}


def load_references(root: Path, agent: str) -> str:
    parts = []
    for ref in REFERENCES[agent]:
        rel = (SKILL_DIR / "references" / f"{ref}.md").as_posix()
        body = _strip_frontmatter((root / rel).read_text(encoding="utf-8"))
        parts.append(f"### Reference file `{rel}` (full text)\n\n{body}")
    return "\n\n".join(parts)


def _sidecar_schema(agent: str) -> str:
    if agent in ANALYSTS or agent == "business":
        return ('{"score": <integer 1-10, the same score stated in your markdown file>, '
                '"summary": "<one sentence>"}')
    if agent == "review":
        return json.dumps({
            "findings": [{"id": "R1", "problem": "...", "evidence": "...", "severity": "HIGH|MEDIUM|LOW",
                          "owner": "moat|management|valuation|mos|report", "required_correction": "..."}],
        }, indent=2)
    return ('{"financial_quality_score": <integer 1-10>, "scores_reported": '
            '{"moat": <int>, "management": <int>, "valuation": <int>, "mos": <int>}}')


def system_prompt(root: Path, paths: Paths, agent: str, company: str, iteration: int, *,
                  high_iteration: int = 0, medium_iteration: int = 0) -> str:
    key = paths.key
    contract = [
        "## RUNTIME CONTRACT (highest priority; overrides paths and details in the instructions above)",
        f"- Target company: {company}. Today's date: {date.today().isoformat()}.",
        f"- `<KEY>` in your instructions is `{key}`: your files live under `research/{key}/` and `reports/{key}/`.",
        f"- Framework reference files are in `{SKILL_DIR.as_posix()}/references/` (relative to the working directory)."
        + (" The ones your instructions name are included in full at the end of this prompt: they are already "
           "read, so do not open them again." if REFERENCES[agent] else ""),
        "- You cannot run shell commands or git. You may only write your own output file and your own sidecar, listed below.",
        f"- Read only markdown files directly in `research/{key}/` (not `_meta/` or `_archive/`), plus the SEC data "
        f"pack `{paths.rel(paths.data_pack)}` and its companion `{paths.rel(paths.data_dir / 'financials.json')}` "
        "(originally filed values of restated figures).",
        f"- SEC data pack: `{paths.rel(paths.data_pack)}` was generated by the workflow directly from the company's "
        "SEC XBRL filings (a primary source) and is shared by every agent in this run. Read it before other research. "
        "Its FACT values carry their filing references and may be cited as SEC filings without fetching those filings "
        "again; its CALCULATION rows show their formulas. Research as usual anything it does not cover or that needs "
        "context (segment detail, narrative, market data, current share price). If it says it is unavailable, "
        "research everything as usual.",
        f"- Main output file: `{paths.rel(paths.output(agent))}`",
        f"- After the main file is saved, write a JSON sidecar to `{paths.rel(paths.sidecar(agent))}` "
        "containing ONLY valid JSON of this shape:",
        _sidecar_schema(agent),
    ]
    if agent in ANALYSTS or agent == "business":
        contract.append(
            "- Label substantive statements in your markdown as FACT, CALCULATION, ASSUMPTION or JUDGMENT, "
            "record source and period for key numbers, and state your 1-10 score explicitly under the word 'Score'.")
    if agent == "review":
        contract += [
            f"- This is review pass {iteration + 1}.",
            f"- HIGH-severity correction rounds already performed: {high_iteration} of {MAX_CORRECTIONS}.",
            f"- MEDIUM-severity correction rounds already performed: {medium_iteration} of {MAX_MEDIUM_CORRECTIONS} "
            "(these only start once no correctable HIGH finding remains; LOW findings are never corrected).",
            "- Give every finding a unique id (R1, R2, ...) and write that id next to the finding in review.md.",
            "- Set `owner` to the single agent whose file must change: moat, management, valuation, mos, "
            "or `report` if only the final report can fix it (e.g. presentation, or anything in business.md: the "
            "report agent turns it into the Company Overview, Business Model and Financial Quality sections).",
            "- Also audit compliance with the project data rules above (for example, an idea attributed to Buffett "
            "without supporting evidence).",
            "- The sidecar `findings` list holds ONLY issues that are open after this review, at every severity. "
            "An issue you verified as fixed is reported as fixed in review.md and left out of the sidecar: the "
            "workflow sends HIGH and MEDIUM findings in the sidecar to their owner for correction (findings owned by "
            "`report` go to the report agent).",
            "- The workflow counts the findings itself and decides what is corrected; you only audit and classify.",
            "- The LAST line of review.md must be exactly `Summary: H HIGH, M MEDIUM, L LOW` with real numbers: "
            "H, M and L equal the number of sidecar findings of each severity.",
        ]
        if high_iteration >= MAX_CORRECTIONS:
            contract.append("- The maximum number of HIGH-severity correction rounds has been reached: any HIGH "
                            "finding owned by moat, management, valuation or mos that you record now will not be "
                            "corrected; it goes to the final report flagged as unresolved.")
        if medium_iteration >= MAX_MEDIUM_CORRECTIONS:
            contract.append("- The maximum number of MEDIUM-severity correction rounds has been reached: any MEDIUM "
                            "finding owned by moat, management, valuation or mos that you record now will not be "
                            "corrected; it goes to the final report flagged as unresolved.")
    if agent == "report":
        contract.append("- Use exactly the upstream scores given in the task for `scores_reported`; do not average them.")
        contract.append("- `financial_quality_score` is the score in the business analysis; change it only where an "
                        "issue owned by the report requires it, and then say in the report why.")
    sections = [
        load_agent_body(root, agent),
        "## Buffett analysis skill (already loaded; follow it)\n" + load_skill_body(root),
        "## Project data rules (from the project's CLAUDE.md; follow them)\n" + load_data_rules(root),
        "\n".join(contract),
    ]
    if REFERENCES[agent]:
        sections.append("## Framework reference files (already loaded; read and apply them as your instructions "
                        "say)\n\n" + load_references(root, agent))
    return "\n\n".join(sections)


def _fmt_findings(findings) -> str:
    return "\n".join(
        f"- [{f.id}] ({f.severity}, owner={f.owner}) Problem: {f.problem}\n  Evidence: {f.evidence}\n"
        f"  Required correction: {f.required_correction}" for f in findings)


def user_prompt(paths: Paths, agent: str, company: str, *, findings=(), upstream_changed: bool = False,
                scores: dict[str, int] | None = None, unresolved=(), report_notes=(), iteration: int = 0,
                high_iteration: int = 0, medium_iteration: int = 0, phase: str | None = None,
                previous_findings=()) -> str:
    parts = [f"Perform your role for the company: {company}."]
    if DEPENDS[agent]:
        parts.append(f"Read your upstream inputs from `research/{paths.key}/` as your instructions describe.")
    if agent in ANALYSTS and (findings or upstream_changed) and iteration:
        round_label = (f"MEDIUM correction round {medium_iteration} of {MAX_MEDIUM_CORRECTIONS}" if phase == "medium"
                       else f"HIGH correction round {high_iteration} of {MAX_CORRECTIONS}")
        why = ("failed independent review" if findings else
               "must be brought up to date because upstream research files it depends on changed in this round")
        todo = ("fix exactly the problems below" + (" and make the analysis consistent with the changed upstream "
                                                   "files" if upstream_changed else "")
                if findings else "re-read the upstream research files and make this analysis consistent with them")
        parts.append(f"\n## CORRECTION RUN ({round_label})\n"
                     f"Your existing file `{paths.rel(paths.output(agent))}` {why}. "
                     f"Update it in place: {todo}; change anything else only where this requires it, "
                     "and rewrite your sidecar. Make the changes as targeted edits (the Edit tool) to the affected "
                     "passages, including every figure or conclusion elsewhere in the file that depends on them, rather "
                     "than rewriting the whole file.")
        if findings:
            parts.append(_fmt_findings(findings))
        if findings and upstream_changed:
            parts.append("Upstream research files also changed in this round; re-read them.")
    if agent == "review" and iteration:
        parts.append(f"\nThis re-reviews corrections made in round {iteration}. Re-audit everything, and explicitly verify "
                     "the previously reported issues are fixed.")
        if previous_findings:
            parts.append("\n## Findings of the previous review pass\n"
                         "State in review.md whether each one is now fixed. Keep the same id for an issue that is still "
                         "open; give each new issue a new id that no earlier finding has used.\n"
                         + _fmt_findings(previous_findings))
    if agent == "report":
        parts.append("\nUpstream scores (use exactly): " + json.dumps(scores or {}))
        if unresolved:
            parts.append("\n## UNRESOLVED ISSUES (left open by the correction loop)\n"
                         "Use your best judgment to resolve each, and clearly flag every one as an unresolved "
                         "issue in the report, labeled with its severity (each item below states HIGH or MEDIUM):\n"
                         + _fmt_findings(unresolved))
        if report_notes:
            parts.append("\n## Issues owned by the report (you must address these)\n" + _fmt_findings(report_notes))
    return "\n".join(parts)


def fix_prompt(errors: list[str]) -> str:
    """Follow-up in the same session after the workflow's validation rejected the saved files."""
    return ("The workflow's validation REJECTED your saved files. Fix these problems and re-save the affected "
            "files (only what is needed to fix them):\n" + "\n".join(f"- {e}" for e in errors))
